kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '5'
    openshift.io/generated-by: OpenShiftNewApp
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"felhofenykepalbum:latest","namespace":"bandi2-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"felhofenykepalbum\")].image","paused":true}]
  resourceVersion: '565035011'
  name: felhofenykepalbum
  uid: ee5188a2-ddd5-4511-b04a-1cbb27516ac7
  creationTimestamp: '2025-03-30T10:08:30Z'
  generation: 5
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2025-03-30T10:08:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"felhofenykepalbum"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-03-30T10:09:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"felhofenykepalbum"}':
                  'f:image': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2025-03-30T10:17:12Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                'f:openshift.openshift.io/restartedAt': {}
            'f:spec':
              'f:containers':
                'k:{"name":"felhofenykepalbum"}':
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/app/media"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:volumes':
                .: {}
                'k:{"name":"mediastore"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-03-30T10:17:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: bandi2-dev
  labels:
    app: felhofenykepalbum
    app.kubernetes.io/component: felhofenykepalbum
    app.kubernetes.io/instance: felhofenykepalbum
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: felhofenykepalbum
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: felhofenykepalbum
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
        openshift.openshift.io/restartedAt: '2025-03-30T10:17:12.541Z'
    spec:
      volumes:
        - name: mediastore
          persistentVolumeClaim:
            claimName: mediastore
      containers:
        - name: felhofenykepalbum
          image: >-
            image-registry.openshift-image-registry.svc:5000/bandi2-dev/felhofenykepalbum@sha256:1491dda4c06cc92e04e115a51cb5d6a4145cec667f27ba1be9afe30d4fd0cf23
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: mediastore
              mountPath: /app/media
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          env: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
status:
  observedGeneration: 5
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-03-30T10:08:32Z'
      lastTransitionTime: '2025-03-30T10:08:32Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-03-30T10:17:14Z'
      lastTransitionTime: '2025-03-30T10:08:30Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "felhofenykepalbum-69b9797b4c" has successfully progressed.
